//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;

    public partial class C_get_ok_days3
    {
        public string fio { get; set; }
        //public Nullable<System.DateTime> datbegin { get; set; }
        public DateTime datbegin { get; set; }
        public string doljn { get; set; }
        public Nullable<int> dday { get; set; }
        public Nullable<int> dmonth { get; set; }
        public string podr { get; set; }
        public string cod { get; set; }
        public Nullable<System.Guid> nrec { get; set; }

        public int Aget { get { return DateTime.Now.Year - Convert.ToInt32(datbegin.Year); } }
        public int Aget1 { get { return DateTime.Now.Year - Convert.ToInt32(datbegin.Year) - 1; } }
       
        public string datroj { get { return Convert.ToString(datbegin.Day) + "." + Convert.ToString(datbegin.Month) + "." + Convert.ToString(datbegin.Year); } }
       
        public DateTime datr { get { return Convert.ToDateTime("01.01.2021"); } }
        public int NowKol { get { return (DateTime.Now.DayOfYear); } }
        public int BirdKol1 { get { return (datbegin.DayOfYear); } }
        public int BirdKol { get { return (datr.DayOfYear); } }
    }
}
