//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_main
    {
        public System.Guid ID { get; set; }
        public System.Guid PARTID { get; set; }
        public string Href { get; set; }
        public string HrefText { get; set; }
        public string Annotation { get; set; }
        public int Sort { get; set; }
        public byte[] msrepl_synctran_ts { get; set; }
    
        public virtual link_parts link_parts { get; set; }
    }
}
