//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_parts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public link_parts()
        {
            this.link_main = new HashSet<link_main>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid TYPEID { get; set; }
        public string PartName { get; set; }
        public string PartImg { get; set; }
        public int Sort { get; set; }
        public byte[] msrepl_synctran_ts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<link_main> link_main { get; set; }
        public virtual link_type link_type { get; set; }
    }
}
