//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhoneEntities : DbContext
    {
        public PhoneEntities()
            : base("name=PhoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<link_main> link_main { get; set; }
        public virtual DbSet<link_parts> link_parts { get; set; }
        public virtual DbSet<link_type> link_type { get; set; }
        public virtual DbSet<ph_department> ph_department { get; set; }
        public virtual DbSet<ph_enterprise> ph_enterprise { get; set; }
        public virtual DbSet<ph_main> ph_main { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<S_News> S_News { get; set; }
    }
}
