//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ph_department()
        {
            this.ph_main = new HashSet<ph_main>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ENTID { get; set; }
        public string DepName { get; set; }
        public string DepShortName { get; set; }
        public Nullable<int> KAT { get; set; }
    
        public virtual ph_enterprise ph_enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ph_main> ph_main { get; set; }
    }
}
