//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_main
    {
        public System.Guid ID { get; set; }
        public System.Guid DEPID { get; set; }
        public string FIO { get; set; }
        public string Dolzhnost { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhoneCity { get; set; }
        public string WorkPhoneCity { get; set; }
        public string EMail { get; set; }
        public string Peiger { get; set; }
        public string PhotoImg { get; set; }
        public Nullable<System.DateTime> BirthDayDate { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<int> KAT { get; set; }
        public byte[] PImage { get; set; }
    
        public virtual ph_department ph_department { get; set; }
    }
}
