//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int IDP { get; set; }
        public string FIO { get; set; }
        public string WorkPhone { get; set; }
        public string Phone1 { get; set; }
        public string Doljnost { get; set; }
    }
}
