//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_News
    {
        public System.Guid ID_News { get; set; }
        public System.DateTime News_Date { get; set; }
        public string N_News { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> L_Akt { get; set; }
    }
}
